name: Check turnos

on:
  schedule:
    - cron: "0 16 * * *"   # todos los días a las 10 AM UTC
  workflow_dispatch:

jobs:
  check-turnos:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.48.0-jammy

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: npm install

      - name: Instalar navegadores Playwright
        run: npx playwright install --with-deps

      - name: Ejecutar script de turnos
        run: npm start
        env:
          USER_MUTUALISTA: ${{ secrets.USER_MUTUALISTA }}
          PASS_MUTUALISTA: ${{ secrets.PASS_MUTUALISTA }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        continue-on-error: true  # permite que el workflow siga y suba capturas aunque falle

      - name: Asegurar carpeta screenshots
        run: mkdir -p screenshots

      - name: Listar screenshots generadas
        run: ls -la screenshots

      - name: Subir capturas como artifact
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: 'screenshots/**'
